apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartKind: pages
    chartRepository: https://github.com/jenkins-x-bdd/repo.git
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kind
    registry: hub.docker.com
  environments:
  - key: dev
    owner: falsedlah
    repository: jx3-k3s-vault
  - key: staging
  ingress:
    domain: alkhaleefi.com
    ignoreLoadBalancer: true
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: fayez@tradingcentral.com
      enabled: false
      production: false
  pipelineUser:
    username: falsedlah
  repository: bucketrepo
  secretStorage: vault
  vault:
    url: http://vault.alkhaleefi.com:8200
  webhook: lighthouse
