apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        falsedlah/jx3-k3s-vault: true
        falsedlah/node-postgresql: true
        falsedlah/spring-boot-gradle: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        falsedlah/jx3-k3s-vault: merge
        falsedlah/node-postgresql: merge
        falsedlah/spring-boot-gradle: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - falsedlah/jx3-k3s-vault
        - falsedlah/node-postgresql
        - falsedlah/spring-boot-gradle
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - falsedlah/jx3-k3s-vault
        - falsedlah/node-postgresql
        - falsedlah/spring-boot-gradle
      target_url: http://lighthouse-jx.alkhaleefi.com/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
